[project]
name = "cn-stock-monitor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "akshare>=1.18.19",
    "pandas>=2.3.3",
    "plotly>=6.5.2",
    "streamlit>=1.50.0",
]
